artifacts_root : artifacts

data_ingestion  : 
  root_dir          : artifacts/datas
  raw_data_path     : artifacts/datas/handwritten.csv
  train_data_path   : artifacts/datas/train.csv
  test_data_path    : artifacts/datas/test.csv
  val_data_path     : artifacts/datas/val.csv

prepare_base_model:
  root_dir                : artifacts/prepare_base_model
  base_model_path         : artifacts/prepare_base_model/base_model.h5
  updated_base_model_path : artifacts/prepare_base_model/base_model_updated.h5

training:
  root_dir                  : artifacts/training
  trained_model_path        : artifacts/training/model.h5

