artifacts_root : artifacts

data_ingestion  : 
  root_dir          : artifacts/datas
  raw_data_path     : artifacts/datas/handwritten.csv
  train_data_path   : artifacts/datas/train.csv
  test_data_path    : artifacts/datas/test.csv
  val_data_path     : artifacts/datas/val.csv